version: '3.4'
services:
  automatic:
    build:
      context: ./automatic_instrumentation
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    ports:
      - '4567:4567'

  manual:
    build:
      context: ./manual_instrumentation
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    ports:
      - '4568:4567'

  jaeger:
    image: 'jaegertracing/all-in-one:1'
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '16686:16686'
